"""initial revision

Revision ID: 3adb8ef43629
Revises: 
Create Date: 2024-09-16 12:23:09.243374+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3adb8ef43629'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adaptationtarget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adaptationtarget_target'), 'adaptationtarget', ['target'], unique=True)
    op.create_index(op.f('ix_adaptationtarget_value'), 'adaptationtarget', ['value'], unique=False)
    op.create_table('naturebasedsolution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('definition', sa.String(), nullable=False),
    sa.Column('cobenefits', sa.String(), nullable=False),
    sa.Column('specificdetails', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_naturebasedsolution_cobenefits'), 'naturebasedsolution', ['cobenefits'], unique=False)
    op.create_index(op.f('ix_naturebasedsolution_definition'), 'naturebasedsolution', ['definition'], unique=False)
    op.create_index(op.f('ix_naturebasedsolution_location'), 'naturebasedsolution', ['location'], unique=False)
    op.create_index(op.f('ix_naturebasedsolution_name'), 'naturebasedsolution', ['name'], unique=True)
    op.create_index(op.f('ix_naturebasedsolution_specificdetails'), 'naturebasedsolution', ['specificdetails'], unique=False)
    op.create_table('nbs_target_assoc',
    sa.Column('nbs_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nbs_id'], ['naturebasedsolution.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['adaptationtarget.id'], ),
    sa.PrimaryKeyConstraint('nbs_id'),
    primary_key=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nbs_target_assoc')
    op.drop_index(op.f('ix_naturebasedsolution_specificdetails'), table_name='naturebasedsolution')
    op.drop_index(op.f('ix_naturebasedsolution_name'), table_name='naturebasedsolution')
    op.drop_index(op.f('ix_naturebasedsolution_location'), table_name='naturebasedsolution')
    op.drop_index(op.f('ix_naturebasedsolution_definition'), table_name='naturebasedsolution')
    op.drop_index(op.f('ix_naturebasedsolution_cobenefits'), table_name='naturebasedsolution')
    op.drop_table('naturebasedsolution')
    op.drop_index(op.f('ix_adaptationtarget_value'), table_name='adaptationtarget')
    op.drop_index(op.f('ix_adaptationtarget_target'), table_name='adaptationtarget')
    op.drop_table('adaptationtarget')
    # ### end Alembic commands ###
