"""Add geometry column to nbs model

Revision ID: 4f84df901480
Revises: 97f61574300b
Create Date: 2024-09-30 12:27:29.119570+00:00

"""

import sqlalchemy as sa
from geoalchemy2 import Geometry

from alembic import op

# revision identifiers, used by Alembic.
revision = "4f84df901480"
down_revision = "97f61574300b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_geospatial_column(
        "naturebasedsolution",
        sa.Column(
            "geometry",
            Geometry(
                srid=4326,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=True,
            ),
            nullable=True,
            spatial_index=True,
        ),
    )
    op.create_geospatial_index(
        "idx_naturebasedsolution_geometry",
        "naturebasedsolution",
        ["geometry"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index(
        "idx_naturebasedsolution_geometry",
        table_name="naturebasedsolution",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_column("naturebasedsolution", "geometry")
    # ### end Alembic commands ###
