"""move adaptation value to association table

Revision ID: 97f61574300b
Revises: 3adb8ef43629
Create Date: 2024-09-16 15:53:14.341960+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f61574300b'
down_revision = '3adb8ef43629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_adaptationtarget_value', table_name='adaptationtarget')
    op.drop_column('adaptationtarget', 'value')
    op.add_column('nbs_target_assoc', sa.Column('value', sa.Integer(), nullable=False))
    op.alter_column('nbs_target_assoc', 'target_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nbs_target_assoc', 'target_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('nbs_target_assoc', 'value')
    op.add_column('adaptationtarget', sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_adaptationtarget_value', 'adaptationtarget', ['value'], unique=False)
    # ### end Alembic commands ###
